import { useEffect, useState } from 'react';
import type { SamplesManifest } from '../types';
import { resolveAssetUrl } from '../lib/format';

type State =
  | { status: 'loading'; manifest: null; error: null }
  | { status: 'ready'; manifest: SamplesManifest; error: null }
  | { status: 'error'; manifest: null; error: string };

/**
 * Loads public/data/samples.json. No backend is involved: the manifest is a
 * static file generated by scripts/build-samples.mjs.
 */
export function useSamples(): State {
  const [state, setState] = useState<State>({
    status: 'loading',
    manifest: null,
    error: null,
  });

  useEffect(() => {
    const controller = new AbortController();

    async function load() {
      try {
        const response = await fetch(resolveAssetUrl('/data/samples.json'), {
          signal: controller.signal,
        });
        if (!response.ok) {
          throw new Error(`samples.json responded ${response.status}`);
        }
        const json = (await response.json()) as SamplesManifest;
        if (!Array.isArray(json?.samples)) {
          throw new Error('samples.json is missing a "samples" array');
        }
        setState({ status: 'ready', manifest: json, error: null });
      } catch (error) {
        if ((error as Error).name === 'AbortError') return;
        setState({
          status: 'error',
          manifest: null,
          error: (error as Error).message || 'Unknown error loading samples.json',
        });
      }
    }

    void load();
    return () => controller.abort();
  }, []);

  return state;
}
